###
POST http://localhost:9000/register/login
content-type: application/json

{
    "id":"13-0840"
}

###s
POST http://localhost:9000/register/signup?position=doctor
content-type: application/json

{
    "id":"11-0842"
}