exports.languages = [
    { "code": "ar", "name": "Arabic" },
    { "code": "bn", "name": "Bengli" },
    { "code": "cs", "name": "Czech" },
    { "code": "da", "name": "Danish" },
    { "code": "de", "name": "German" },
    { "code": "de-AT", "name": "German (Austria)" },
    { "code": "de-CH", "name": "German (Switzerland)" },
    { "code": "de-DE", "name": "German (Germany)" },
    { "code": "el", "name": "Greek" },
    { "code": "en", "name": "English" },
    { "code": "en-AU", "name": "English (Australia)" },
    { "code": "en-CA", "name": "English (Canada)" },
    { "code": "en-GB", "name": "English (Great Britain)" },
    { "code": "en-IN", "name": "English (India)" },
    { "code": "en-NZ", "name": "English (New Zeland)" },
    { "code": "en-SG", "name": "English (Singapore)" },
    { "code": "en-US", "name": "English (United States)" },
    { "code": "es", "name": "Spanish" },
    { "code": "es-AR", "name": "Spanish (Argentina)" },
    { "code": "es-ES", "name": "Spanish (Spain)" },
    { "code": "es-UY", "name": "Spanish (Uruguay)" },
    { "code": "fi", "name": "Finnish" },
    { "code": "fr", "name": "French" },
    { "code": "fr-BE", "name": "French (Belgium)" },
    { "code": "fr-CH", "name": "French (Switzerland)" },
    { "code": "fr-FR", "name": "French (France)" },
    { "code": "fy   ", "name": "Frysian" },
    { "code": "fy-NL", "name": "Frysian (Netherlands)" },
    { "code": "hi   ", "name": "Hindi" },
    { "code": "hr   ", "name": "Croatian" },
    { "code": "it   ", "name": "Italian" },
    { "code": "it-CH", "name": "Italian (Switzerland)" },
    { "code": "it-IT", "name": "Italian (Italy)" },
    { "code": "ja   ", "name": "Japanese" },
    { "code": "ko   ", "name": "Korean" },
    { "code": "nl   ", "name": "Dutch" },
    { "code": "nl-BE", "name": "Dutch (Belgium)" },
    { "code": "nl-NL", "name": "Dutch (Netherlands)" },
    { "code": "no   ", "name": "Norwegian" },
    { "code": "no-NO", "name": "Norwegian (Norway)" },
    { "code": "pa   ", "name": "Punjabi" },
    { "code": "pl   ", "name": "Polish" },
    { "code": "pt   ", "name": "Portuguese" },
    { "code": "pt-BR", "name": "Portuguese (Brazil)" },
    { "code": "ru   ", "name": "Russian" },
    { "code": "ru-RU", "name": "Russian (Russia)" },
    { "code": "sr   ", "name": "Serbian" },
    { "code": "sr-RS", "name": "Serbian (Serbia)" },
    { "code": "sv   ", "name": "Swedish" },
    { "code": "sv-SE", "name": "Swedish (Sweden)" },
    { "code": "te   ", "name": "Telegu" },
    { "code": "zh   ", "name": "Chinese" },
    { "code": "zh-CN", "name": "Chinese (China)" },
    { "code": "zh-HK", "name": "Chinese (Hong Kong)" },
    { "code": "zh-SG", "name": "Chinese (Singapore)" },
    { "code": "zh-TW", "name": "Chinese (Taiwan)" }
]