###
post http://localhost:7000/login/patient
content-type: application/json

{
    "id":"20210811-206149",
    "password":"user123"
}

###
post http://localhost:7000/login/doctor
content-type: application/json

{
    "id":"777333",
    "password":"secretLuffy"
}