###
post http://localhost:7000/password
content-type: application/json

{
    "id":"20000707-513569",
    "password":"user123"
}

###
patch http://localhost:7000/password
content-type: application/json

{
    "id":"20000101-359062",
    "oldPassword":"user123",
    "newPassword":"user333"
}

###
post http://localhost:7000/password/doctor
content-type: application/json

{
    "id":"777333",
    "password":"secretLuffy"
}

###
patch http://localhost:7000/password/doctor
content-type: application/json

{
    "id":"777333",
    "oldPassword":"secretLuffy",
    "newPassword":"secretLuffy3"
}