###
POST http://localhost:7000/signup/patient
content-type: application/json

{
    "address":"bhaktapur",
    "contactInfo":"9841756432",
    "dob":"2001-01-01",
    "email":"nbhn333@gmail.com",
    "emergencyContactName":"Hari",
    "emergencyContactNo":"9876543210",
    "emergencyContactRltn":"Father",
    "gender":"Male",
    "language":"Neplai",
    "maritalStatus":"Married",
    "name":"Ram Gopal Sharma",
    "zipCode":"46000",
    "photo":"https://media.istockphoto.com/vectors/big-data-and-artificial-intelligence-concept-vector-id1040557296"
}

###

POST http://localhost:7000/signup/doctor
content-type: application/json

{
    "address":"bhaktapur",
    "contactInfo":"9841756432",
    "dob":"1995-01-01",
    "email":"lalbhadur@gmail.com",
    "gender":"Male",
    "language":"Neplai",
    "name":"Lal Bahadur Sharma",
    "zipCode":"47000",
    "photo":"https://media.istockphoto.com/vectors/big-data-and-artificial-intelligence-concept-vector-id1040557296",
    "qualification":"MBBS"
}

###

post http://localhost:7000/login/patient
content-type: application/json

{
    "id":"2021-05-0644600",
    "password":"user1234"
}

###
post http://localhost:7000/password
content-type: application/json

{
    "id":"2001-01-0146000",
    "password":"secretLuffy"
}

###
patch http://localhost:7000/password
content-type: application/json

{
    "id":"2001-01-0146000",
    "oldPassword":"secretLuffy",
    "newPassword":"secretLuffy3"
}

###

GET http://localhost:7000/signup/data
content-type: application/json

{
    "id":"2010-03-2142600"
}

###
GET http://localhost:7000/report?reportName=ac.pdf

###
POST http://localhost:7000/report
content-type: application/json

{
    "id":"o1010"
}










###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"khatri",
"firstName":"Babin",
"middleName":"",
"prefix":"Er",
"suffix":"PHD",
"mobileNo":"9876543210",
"email":"presentator7@gmail.com",
"gender":"Male",
"dob":"2000-01-01",
"city":"Gothatar",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6139",
"streetName":"Kageshwori",
"postalCode":"4567",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"data:image/jpeg;base64,/9j/6RRSYdATgZe0HwVPyP9DFFHehOwtP8UuNxH85RRScu1zpGpwP85TNPKPFNMOmWYycI0UU1ZJNwgaPGKKKnB1k4ooyNFFFAn//2Q==",
"languageCode":"en-US",
"language":"English"
}

###
post http://localhost:7000/login/patient
content-type: application/json

{
    "id":"20000101-933873",
    "password":"secretLuffy"
}

###
post http://localhost:7000/password
content-type: application/json

{
    "id":"20000101-933873",
    "password":"secretLuffy"
}

###
patch http://localhost:7000/password
content-type: application/json

{
    "id":"20000101-933873",
    "oldPassword":"secretLuffy",
    "newPassword":"secretLuffy3"
}