###
GET http://localhost:7000/report?reportName=ReportSample copy.pdf&id=20000101-687825&masterId=12345
###
GET http://localhost:7000/record?recordName=ReportSample copy.pdf&id=20000101-687825

###
POST http://localhost:7000/report
content-type: application/json

{
    "id":"o1010"
}

###
GET http://localhost:7000/search?patientId=20000101-494315









###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"khatri",
"firstName":"Babin",
"middleName":"",
"prefix":"Er",
"suffix":"PHD",
"mobileNo":"9876543210",
"email":"akgunner6@gmail.com",
"gender":"Male",
"dob":"2000-01-01",
"city":"Gothatar",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6139",
"streetName":"Kageshwori",
"postalCode":"4567",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"data:image/jpeg;base64,/9j/6RRSYdATgZe0HwVPyP9DFFHehOwtP8UuNxH85RRScu1zpGpwP85TNPKPFNMOmWYycI0UU1ZJNwgaPGKKKnB1k4ooyNFFFAn//2Q==",
"languageCode":"en-US",
"language":"English"
}

###
post http://localhost:7000/login/patient
content-type: application/json

{
    "id":"20000101-494315",
    "password":"user123"
}

###
post http://localhost:7000/password
content-type: application/json

{
    "id":"20000101-494315",
    "password":"user123"
}

###
patch http://localhost:7000/password
content-type: application/json

{
    "id":"20000101-494315",
    "oldPassword":"user123",
    "newPassword":"user333"
}

###

POST http://localhost:7000/signup/doctor
content-type: application/json

{
"id":"777333",
"lastName":"khatri",
"firstName":"Babin",
"middleName":"",
"prefix":"Er",
"suffix":"PHD",
"mobileNo":"9876543210",
"email":"presentator7@gmail.com",
"gender":"Male",
"dob":"2000-01-01",
"city":"Gothatar",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6139",
"streetName":"Kageshwori",
"postalCode":"4567",
"qualificationCodeSystem":"trial",
"qualificationCodeCode":"trial",
"qualificationCodeDisplay":"trial",
"qualificationCodetext":"trial",
"qualificationIdentifierSystem":"trial",
"qualificationIdentifierValue":"trial",
"periodStart":"trial",
"issuer":"trial",
"photo":"data:image/jpeg;base64,/9j/",
"languageCode":"en-US",
"language":"English"
}

###
post http://localhost:7000/password/doctor
content-type: application/json

{
    "id":"777333",
    "password":"secretLuffy"
}

###
patch http://localhost:7000/password/doctor
content-type: application/json

{
    "id":"777333",
    "oldPassword":"secretLuffy",
    "newPassword":"secretLuffy3"
}

###
post http://localhost:7000/login/doctor
content-type: application/json

{
    "id":"777333",
    "password":"secretLuffy"
}