POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"Ghimire",
"firstName":"Ram",
"middleName":"",
"prefix":"Er.",
"suffix":"",
"mobileNo":"9876543210",
"email":"presentator39@gmail.com",
"gender":"Male",
"dob":"2000-01-01",
"city":"Kageshowri",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6139",
"streetName":"Manohara",
"postalCode":"4567",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"https://firebasestorage.googleapis.com/v0/b/wedding-helper-21354.appspot.com/o/hostphoto%2Fbabin.jpg?alt=media&token=a780fcab-4669-4fe7-8c03-41ea78874a02",
"languageCode":"en-US",
"language":"English"
}

###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"Khatiwada",
"firstName":"Ankit",
"middleName":"",
"prefix":"Er.",
"suffix":"",
"mobileNo":"+9779861222013",
"email":"akgunner6@gmail.com",
"gender":"Male",
"dob":"2000-05-07",
"city":"Madhyapur Thimi",
"district":"Bhaktapur",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"3961",
"streetName":"Gatthaghar Chowk",
"postalCode":"6745",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"https://firebasestorage.googleapis.com/v0/b/wedding-helper-21354.appspot.com/o/hostphoto%2Fankit.jpg?alt=media&token=35241342-5d11-49af-9dde-dfdf44872942",
"languageCode":"en-US",
"language":"English"
}

###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"Ghimire",
"firstName":"Nabin",
"middleName":"",
"prefix":"Er.",
"suffix":"",
"mobileNo":"9851444720",
"email":"nabinghimire203@gmail.com",
"gender":"Male",
"dob":"2000-03-03",
"city":"Nawalpur",
"district":"Chitwan",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6193",
"streetName":"Nabin Galli",
"postalCode":"4576",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"https://firebasestorage.googleapis.com/v0/b/mhpd-652a9.appspot.com/o/images%2FIMG-e09c38d7f5b428b81a65ef61f6ebbf26-V.jpg?alt=media&token=725c4698-a0b5-465e-ad2e-49a6e6b26b16",
"languageCode":"en-US",
"language":"English"
}

###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"Sharma",
"firstName":"Shyam",
"middleName":"",
"prefix":"Er.",
"suffix":"",
"mobileNo":"9849102435",
"email":"nbhn333@gmail.com",
"gender":"Male",
"dob":"2000-07-07",
"city":"Gokarna",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"1639",
"streetName":"Panchkanya",
"postalCode":"5467",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"https://firebasestorage.googleapis.com/v0/b/wedding-helper-21354.appspot.com/o/hostphoto%2Fnischal.jpg?alt=media&token=de224913-49ac-4fe2-ae88-3996eeb39469",
"languageCode":"en-US",
"language":"English"
}

###
POST http://localhost:7000/signup/patient
content-type: application/json

{

"lastName":"Ghanashyam",
"firstName":"Hari",
"middleName":"",
"prefix":"Mr.",
"suffix":"PHD",
"mobileNo":"9876543210",
"email":"presentator7@gmail.com",
"gender":"Male",
"dob":"2000-01-01",
"city":"Gothatar",
"district":"Kathmandu",
"state":"Bagmati",
"country":"Nepal",
"houseNo":"6139",
"streetName":"Kageshwori",
"postalCode":"4567",
"maritialStatusCode":"S",
"maritialStatus":"Single",
"multipleBirthBoolean":false,
"birthOrder":1,
"photo":"",
"languageCode":"en-US",
"language":"English"
}

###