function mapRecordType(typeName) {
    const procedure = [
        { code: "104001 ", name: "Excision of lesion of patella" },
        { code: "115006 ", name: "Fit removable orthodontic appliance" },
        { code: "119000 ", name: "Thoracoscopic partial lobectomy of lung" },
        { code: "121005 ", name: "Retrobulbar injection of therapeutic agent" },
        { code: "128004 ", name: "Hand microscope examination of skin" },
        { code: "133000 ", name: "Percutaneous implantation of neurostimulator electrodes into neuromuscular component" },
        { code: "135007 ", name: "Arthrotomy of wrist joint with exploration and biopsy" },
        { code: "142007 ", name: "Excision of tumor from shoulder area, deep, intramuscular" },
        { code: "146005 ", name: "Repair of nonunion of metatarsal with bone graft" },
        { code: "153001 ", name: "Cystourethroscopy with resection of ureterocele" },
        { code: "160007 ", name: "Removal of foreign body of tendon and/or tendon sheath" },
        { code: "166001 ", name: "Behavioral therapy" },
        { code: "170009 ", name: "Special potency disk identification, vancomycin test" },
        { code: "174000 ", name: "Harrison-Richardson operation on vagina" },
        { code: "176003 ", name: "Anastomosis of rectum" },
        { code: "189009 ", name: "Excision of lesion of artery" },
        { code: "197002 ", name: "Mold to yeast conversion test" },
        { code: "230009 ", name: "Miller operation, urethrovesical suspension" },
        { code: "243009 ", name: "Replacement of cerebral ventricular tube" },
        { code: "245002 ", name: "Division of nerve ganglion" },
        { code: "262007 ", name: "Percutaneous aspiration of renal pelvis" },
        { code: "267001 ", name: "Anal fistulectomy, multiple" },
        { code: "285008 ", name: "Incision and drainage of vulva" },
        { code: "294002 ", name: "Excisional biopsy of joint structure of spine" },
        { code: "295001 ", name: "Nonexcisional destruction of cyst of ciliary body" },
        { code: "306005 ", name: "US kidneys" },
        { code: "316002 ", name: "Partial dacryocystectomy" },
        { code: "334003 ", name: "Panorex examination of mandible" },
        { code: "342002 ", name: "Amobarbital interview" },
        { code: "346004 ", name: "Periodontal scaling and root planing, per quadrant" },
        { code: "348003 ", name: "Radionuclide dynamic function study" },
        { code: "351005 ", name: "Urinary undiversion of ureteral anastomosis" },
        { code: "352003 ", name: "Reagent RBC, preparation antibody sensitized pool" },
        { code: "353008 ", name: "IV/irrigation monitoring" },
        { code: "374009 ", name: "Costosternoplasty for pectus excavatum repair" },
        { code: "388008 ", name: "Blepharorrhaphy" },
        { code: "389000 ", name: "Tobramycin level" },
        { code: "401004 ", name: "Distal subtotal pancreatectomy" },
        { code: "406009 ", name: "Fulguration of stomach lesion" },
        { code: "417005 ", name: "Hospital re-admission" },
        { code: "435001 ", name: "Pulmonary inhalation study" },
        { code: "445004 ", name: "Repair of malunion of tibia" },
        { code: "456004 ", name: "Total abdominal colectomy with ileostomy" },
        { code: "459006 ", name: "Closed condylotomy of mandible" },
        { code: "463004 ", name: "Closed reduction of coxofemoral joint dislocation with splint" },
        { code: "468008 ", name: "Glutathione measurement" },
        { code: "474008 ", name: "Esophagoenteric anastomosis, intrathoracic" },
        { code: "489004 ", name: "Ferritin level" },
        { code: "493005 ", name: "Urobilinogen measurement, 48-hour, feces" },
        { code: "494004 ", name: "Excision of lesion of tonsil" },
        { code: "497006 ", name: "Replacement of cochlear prosthesis, multiple channels" },
        { code: "503003 ", name: "Corneal gluing" },
        { code: "531007 ", name: "Open pulmonary valve commissurotomy with inflow occlusion" },
        { code: "533005 ", name: "Repair of vesicocolic fistula" },
        { code: "535003 ", name: "Closure of ureterovesicovaginal fistula" },
        { code: "540006 ", name: "Antibody to single and double stranded DNA measurement" },
        { code: "543008 ", name: "Choledochostomy with transduodenal sphincteroplasty" },
        { code: "545001 ", name: "Operative procedure on lower leg" },
        { code: "549007 ", name: "Incision of intracranial vein" },
        { code: "550007 ", name: "Excision of lesion of adenoids" },
        { code: "559008 ", name: "Excision of varicose vein" },
        { code: "570001 ", name: "Vaccination for arthropod-borne viral encephalitis" },
        { code: "574005 ", name: "Benzodiazepine measurement" },
        { code: "603006 ", name: "Synchondrotomy" },
        { code: "617002 ", name: "Bone graft of mandible" },
        { code: "618007 ", name: "Frontal sinusectomy" },
        { code: "625000 ", name: "Removal of supernumerary digit" },
        { code: "628003 ", name: "Steinman test" },
        { code: "629006 ", name: "Lysis of adhesions of urethra" },
        { code: "633004 ", name: "Chart review by physician" },
        { code: "637003 ", name: "Lysis of adhesions of nose" },
        { code: "642006 ", name: "Cerebral thermography" },
        { code: "645008 ", name: "Diagnostic procedure on vitreous" },
        { code: "647000 ", name: "Excision of cervix by electroconization" },
        { code: "657004 ", name: "Operation on bursa" },
        { code: "665001 ", name: "Partial meniscectomy of temporomandibular joint" },
        { code: "670008 ", name: "Electrosurgical epilation of eyebrow" },
        { code: "671007 ", name: "Transplantation of testis" },
        { code: "673005 ", name: "Indirect examination of larynx" },
        { code: "674004 ", name: "Abduction test" },
        { code: "676002 ", name: "Peritoneal dialysis including cannulation" },
        { code: "680007 ", name: "Radiation physics consultation" },
        { code: "687005 ", name: "Albumin/Globulin ratio" },
        { code: "695009 ", name: "Destructive procedure of lesion on skin of trunk" },
        { code: "697001 ", name: "Hepatitis A virus antibody measurement" },
        { code: "710006 ", name: "Thromboendarterectomy with graft of mesenteric artery" },
        { code: "712003 ", name: "Closed chest suction" },
        { code: "721002 ", name: "Medical procedure on periurethral tissue" },
        { code: "722009 ", name: "Fine needle biopsy of thymus" },
        { code: "726007 ", name: "Pathology consultation, comprehensive, records and specimen with report" },
        { code: "730005 ", name: "Incision of subcutaneous tissue" },
        { code: "741007 ", name: "Operation on prostate" },
        { code: "746002 ", name: "Chiropractic adjustment of coccyx subluxation" },
        { code: "753006 ", name: "Manipulation of ankle AND foot" },
        { code: "754000 ", name: "Total urethrectomy" },
        { code: "759005 ", name: "Intracerebral electroencephalogram" },
        { code: "762008 ", name: "Computerized axial tomography of cervical spine with contrast" },
        { code: "764009 ", name: "Arthrodesis of interphalangeal joint of great toe" },
        { code: "767002 ", name: "White blood cell count - observation" },
        { code: "789003 ", name: "Cranial decompression, subtemporal, supratentorial" },
        { code: "791006 ", name: "Dressing and fixation procedure" },
        { code: "807005 ", name: "Excision of brain" },
        { code: "814007 ", name: "Electrophoresis measurement" },
        { code: "817000 ", name: "Excision of cyst of spleen" },
        { code: "831000 ", name: "Drawer test" },
        { code: "851001 ", name: "Root canal therapy, molar, excluding final restoration" },
        { code: "853003 ", name: "Fecal fat measurement, 72-hour collection" },
        { code: "867007 ", name: "Hypoglossofacial anastomosis" },
        { code: "870006 ", name: "Carbamazepine measurement" },
        { code: "879007 ", name: "Special blood coagulation test, explain by report" },
        { code: "881009 ", name: "Separation of ciliary body" },
        { code: "893000 ", name: "Tumor antigen measurement" },
        { code: "897004 ", name: "Radical maxillary antrotomy" },
        { code: "910002 ", name: "MHPG measurement, urine" },
        { code: "911003 ", name: "Removal of subarachnoid-ureteral shunt" },
        { code: "913000 ", name: "Chiropractic patient education" },
        { code: "926001 ", name: "Embolectomy with catheter of radial artery by arm incision" },
        { code: "935008 ", name: "Excision of bulbourethral gland" },
        { code: "941001 ", name: "Endoscopy of pituitary gland" },
        { code: "945005 ", name: "Excision of tibia and fibula for graft" },
        { code: "948007 ", name: "Phlebectomy of intracranial varicose vein" },
        { code: "951000 ", name: "Ultrasonic guidance for endomyocardial biopsy" },
        { code: "956005 ", name: "Anesthesia for procedure on thoracic esophagus" },
        { code: "967006 ", name: "Drug treatment education" },
        { code: "969009 ", name: "Incision and exploration of larynx" },
        { code: "971009 ", name: "Prosthetic construction and fitting" },
        { code: "1001000", name: "Cauterization of Bartholin's gland" },
        { code: "1008006", name: "Operation on nerve ganglion" },
        { code: "1019009", name: "Removal of corneal epithelium" },
        { code: "1021004", name: "Repair of scrotum" },
        { code: "1029002", name: "Fetoscopy" },
        { code: "1032004", name: "Enucleation of parotid gland cyst" },
        { code: "1035002", name: "Minimum bactericidal concentration test, microdilution method" },
        { code: "1036001", name: "Insertion of intravascular device in common iliac vein, complete" },
        { code: "1041009", name: "Debridement of open fracture of phalanges of foot" },
        { code: "1042002", name: "Paternity testing" },
        { code: "1043007", name: "Doppler color flow velocity mapping" },
        { code: "1044001", name: "Diagnostic ultrasound of abdomen and retroperitoneum" },
        { code: "1048003", name: "Capillary blood sampling" },
        { code: "1054002", name: "Sphincterotomy of papilla of Vater" },
        { code: "1071001", name: "Proximal splenorenal anastomosis" },
        { code: "1084005", name: "Excision of perinephric cyst" },
        { code: "1093006", name: "Excision of abdominal varicose vein" },
        { code: "1103000", name: "Transcrural mobilization of stapes" },
        { code: "1104006", name: "Triad knee repair" },
        { code: "1115001", name: "Decortication" },
        { code: "1119007", name: "Closed reduction of dislocation of foot and toe" },
        { code: "1121002", name: "Kinetic activities for range of motion" },
        { code: "1127003", name: "Interstitial radium application" },
        { code: "1133007", name: "Removal of intact mammary implant, bilateral" },
        { code: "1163003", name: "Ureteroenterostomy" },
        { code: "1176009", name: "Incision of inguinal region" },
        { code: "1181000", name: "Excision of tendon for graft" },
        { code: "1186005", name: "Anesthesia for procedure on bony pelvis" },
        { code: "1198000", name: "Excisional biopsy of bone of scapula" },
        { code: "1209007", name: "Arthroscopic repair lateral meniscus" },
        { code: "1225002", name: "Upper arm X-ray" },
        { code: "1227005", name: "Incision of subvalvular tissue for discrete subvalvular aortic stenosis" },
        { code: "1235008", name: "Muscle transfer" },
        { code: "1237000", name: "Application of cast, sugar tong" },
        { code: "1238005", name: "Epiphyseal arrest by stapling of distal radius" },
        { code: "1251000", name: "Incisional biopsy of testis" },
        { code: "1253002", name: "Refusion of spine" },
        { code: "1258006", name: "Excision of meniscus of wrist" },
        { code: "1266002", name: "Closure of tympanic membrane perforation" },
        { code: "1267006", name: "Electrocoagulation of lesion of vagina" },
        { code: "1278003", name: "Open reduction of closed shoulder dislocation with fracture of greater tuberosity" },
        { code: "1279006", name: "Repair of cardiac pacemaker pocket in skin AND/OR subcutaneous tissue" },
        { code: "1292009", name: "MRI of bladder" },
        { code: "1299000", name: "Excision of appendiceal stump" },
        { code: "1315009", name: "Reconstruction of eyebrow" },
        { code: "1316005", name: "Upper partial denture, cast metal base without resin saddles, including any conventional clasps, rests and teeth" },
        { code: "1324000", name: "Cerebrospinal fluid immunoglobulin G ratio and immunoglobulin G index" },
        { code: "1327007", name: "Procedure on Meckel diverticulum" },
        { code: "1328002", name: "Ilioiliac shunt" },
        { code: "1329005", name: "Division of congenital web of larynx" },
        { code: "1337002", name: "Colosigmoidostomy" },
        { code: "1339004", name: "Manual evacuation of feces" },
        { code: "1347004", name: "Medical procedure on palate" },
        { code: "1352009", name: "Anterior spinal rhizotomy" },
        { code: "1358008", name: "Anti-human globulin test, enzyme technique, titer" },
        { code: "1366004", name: "Breathing treatment" },
        { code: "1385001", name: "Echography, scan B-mode for foetal age determination" },
        { code: "1390003", name: "Laparoscopic sigmoid colectomy" },
        { code: "1398005", name: "Direct thrombectomy of iliac vein by leg incision" },
        { code: "1399002", name: "Incision and exploration of ureter" },
        { code: "1407007", name: "Application of long leg cast, brace type" },
        { code: "1410000", name: "Anesthesia for tympanotomy" },
        { code: "1411001", name: "Operation on papillary muscle of heart" },
        { code: "1413003", name: "Penetrating keratoplasty with homograft" },
        { code: "1414009", name: "Angiography of arteriovenous shunt" },
        { code: "1417002", name: "Operation on face" },
        { code: "1431002", name: "pexy" },
        { code: "1440003", name: "Repair with resection-recession" },
        { code: "1449002", name: "Removal of hair" },
        { code: "1455007", name: "Cerclage" },
        { code: "1453000", name: "Biofeedback, galvanic skin response" },
        { code: "1457004", name: "Truncal vagotomy with pyloroplasty and gastrostomy" },
        { code: "1494008", name: "Osmolarity measurement" },
        { code: "1500007", name: "Bilateral epididymovasostomy" },
        { code: "1501006", name: "Altemeier operation, perineal rectal pull-through" },
        { code: "1505002", name: "Hospital admission for isolation" },
        { code: "1529009", name: "Aspiration of soft tissue" },
        { code: "1533002", name: "Ureteroplication" },
        { code: "1550000", name: "Amikacin level" },
        { code: "1555005", name: "Brief group psychotherapy" },
        { code: "1559004", name: "Interleukin (IL)-2 assay" },
        { code: "1576000", name: "Repair of intestinouterine fistula" },
        { code: "1577009", name: "Implantation of cardiac single-chamber device replacement, rate-responsive" },
        { code: "1578004", name: "Reconstruction of ossicles with stapedectomy" },
        { code: "1583007", name: "Tractotomy of mesencephalon" },
        { code: "1585000", name: "Lengthening of gastrocnemius muscle" },
        { code: "1596008", name: "Anesthesia for total elbow replacement" },
        { code: "1597004", name: "Skeletal X-ray of ankle and foot" },
        { code: "1602006", name: "Social service interview with planning" },
        { code: "1614003", name: "Bilateral repair of inguinal hernia, direct" },
        { code: "1615002", name: "Reline upper partial denture, chairside" },
        { code: "1616001", name: "Galactosylceramide beta-galactosidase measurement, leukocytes" },
        { code: "1636000", name: "Injection of sclerosing agent in varicose vein" },
        { code: "1638004", name: "Cineplasty with cineplastic prosthesis of extremity" },
        { code: "1640009", name: "History and physical examination, insurance" },
        { code: "1645004", name: "Transduodenal sphincterotomy" },
        { code: "1651009", name: "Excision of tendon sheath" },
        { code: "1653007", name: "Internal fixation of bone without fracture reduction" },
        { code: "1669000", name: "Making occupied bed" },
        { code: "1677001", name: "Haagensen test" },
        { code: "1678006", name: "Endoscopic procedure of nerve" },
        { code: "1680000", name: "Secondary chemoprophylaxis" },
        { code: "1683003", name: "Direct closure of laceration of conjunctiva" },
        { code: "1689004", name: "Local excision of ovary" },
        { code: "1691007", name: "Drainage of abscess of tonsil" },
        { code: "1699009", name: "Special dosimetry" },
        { code: "1702002", name: "Labial veneer, resin laminate, laboratory" },
        { code: "1704001", name: "Correction of tibial pseudoarthrosis" },
        { code: "1709006", name: "Breast reconstruction, bilateral, with bilateral pedicle transverse rectus abdominis myocutaneous flaps" },
        { code: "1712009", name: "Immunoglobulin typing, immunoglobulin G" },
        { code: "1713004", name: "Hypothermia, total body, induction and maintenance" },
        { code: "1730002", name: "Suture of skin wound of hindfoot" },
        { code: "1746005", name: "Buckling of sclera using implant" },
        { code: "1747001", name: "Replacement of skeletal muscle stimulator" },
        { code: "1753001", name: "Resection of uveal tissue" },
        { code: "1757000", name: "Arthroscopy of wrist with partial synovectomy" },
        { code: "1759002", name: "Assessment of nutritional status" },
        { code: "1770009", name: "Mitral valvotomy" },
        { code: "1774000", name: "Nasopharyngeal rehabilitation" },
        { code: "1775004", name: "Submaxillary incision with drainage" },
        { code: "1784004", name: "Fecal stercobilin, qualitative" },
        { code: "1787006", name: "Ultrasonic guidance for pericardiocentesis" },
        { code: "1788001", name: "Blood unit collection for directed donation, donor" },
        { code: "1801001", name: "Endoscopic biopsy of duodenum" },
        { code: "1805005", name: "Take-down of stoma" },
        { code: "1811008", name: "Aspiration of bursa of hand" },
        { code: "1813006", name: "Cryotherapy of genital warts" },
        { code: "1820004", name: "Ethanol measurement, breath" },
        { code: "1830008", name: "Open reduction of open sacral fracture" },
        { code: "1836002", name: "Excision of diverticulum of ventricle of heart" },
        { code: "1844002", name: "Plication of ligament" },
        { code: "1854003", name: "Incision of nose" },
        { code: "1859008", name: "Hand tendon foreign body removed" },
        { code: "1861004", name: "Anesthesia for closed procedure on humerus and elbow" },
        { code: "1862006", name: "Thoracic phlebectomy" },
        { code: "1866009", name: "Bilateral total nephrectomy" },
        { code: "1868005", name: "FB - Removal of foreign body from brain" },
        { code: "1870001", name: "Insertion of halo device of skull with synchronous skeletal traction" },
        { code: "1871002", name: "Repair of aneurysm of coronary artery" },
        { code: "1872009", name: "Suture of male perineum" },
        { code: "1876007", name: "Recession of prognathic jaw" },
        { code: "1879000", name: "Fluorescent antigen measurement" },
        { code: "1889001", name: "Patient transfer, in-hospital, unit-to-unit" },
        { code: "1906007", name: "Insertion of prosthesis or prosthetic device of arm, bioelectric or cineplastic" },
        { code: "1907003", name: "Bifurcation of bone" },
        { code: "1917008", name: "Patient discharge, deceased, medicolegal case" },
        { code: "1924009", name: "Hepaticotomy with drainage" },
        { code: "1950008", name: "Drainage of nasal septal abscess" },
        { code: "1958001", name: "Grafting of bone of thumb with transfer of skin flap" },
        { code: "1966005", name: "Central block anesthesia" },
        { code: "1983001", name: "Total urethrectomy including cystostomy in female" },
        { code: "1995001", name: "Stripping of cerebral meninges" },
        { code: "1999007", name: "Psychologic test" },
        { code: "2002009", name: "Construction of subcutaneous tunnel without esophageal anastomosis" },
        { code: "2021001", name: "Internal fixation of radius and ulna without fracture reduction" },
        { code: "2051007", name: "Red cell iron utilization study" },
        { code: "2054004", name: "Barbiturates measurement, quantitative and qualitative" },
        { code: "2067001", name: "Implantation of electromagnetic hearing aid" },
        { code: "2069003", name: "Dental subperiosteal implant" },
        { code: "2078009", name: "Puncture of bursa of hand" },
        { code: "2079001", name: "Reimplantation of anomalous pulmonary artery" },
        { code: "2080003", name: "Angiectomy with anastomosis of lower limb artery" },
        { code: "2098004", name: "Open reduction of open mandibular fracture with external fixation" },
        { code: "2115003", name: "Dental prophylaxis, children" },
        { code: "2119009", name: "Repair of blood vessel" },
        { code: "2127000", name: "Reduction of closed sacral fracture" },
        { code: "2137005", name: "Excision of pericardial tumor" },
        { code: "2153008", name: "Cardiac catheterization education" },
        { code: "2161003", name: "Operation on vulva" },
        { code: "2164006", name: "Injection of aorta" },
        { code: "2166008", name: "Bicuspidization of aortic valve" },
        { code: "2171001", name: "Excision of tonsil tags" },
        { code: "2178007", name: "Ureterocentesis" },
        { code: "2181002", name: "Operation for bone injury of tarsals and metatarsals" },
        { code: "2188008", name: "Suture of tendon to skeletal attachment" },
        { code: "2193006", name: "Repair of ruptured aneurysm with graft of celiac artery" },
        { code: "2196003", name: "Gas liquid chromatography, electron capture type" },
        { code: "2199005", name: "Excision of lesion of cul-de-sac" },
        { code: "2214008", name: "Curette test of skin" },
        { code: "2220009", name: "Complement component assay" },
        { code: "2225004", name: "Sensititer system test" },
        { code: "2234009", name: "Proctosigmoidopexy" },
        { code: "2238007", name: "Stone operation, anoplasty" },
        { code: "2242005", name: "Reconstruction of eyelid" },
        { code: "2244006", name: "Arthroscopy of wrist with internal fixation for instability" },
        { code: "2250001", name: "Resection of ascending aorta with anastomosis" },
        { code: "2252009", name: "Hospital admission, urgent, 48 hours" },
        { code: "2266004", name: "Venography of adrenal, bilateral" },
        { code: "2267008", name: "Replacement of tracheostomy tube" },
        { code: "2270007", name: "Correction of cleft hand" },
        { code: "2276001", name: "Exploration of popliteal artery" },
        { code: "2278000", name: "Urinalysis, automated" },
        { code: "2279008", name: "Antibody detection, red blood cell, enzyme, 1 stage technique, including anti-human globulin" },
        { code: "2290003", name: "Microbial culture, anaerobic, initial isolation" },
        { code: "2315006", name: "Brain meninges operation" },
        { code: "2318008", name: "Anesthesia for cast procedure on forearm, wrist or hand" },
        { code: "2321005", name: "Delivery by Ritgen maneuver" },
        { code: "2322003", name: "Suture of recent wound of eyelid, direct closure, full-thickness" },
        { code: "2337004", name: "Adductor tenotomy" },
        { code: "2344008", name: "Complicated cystorrhaphy" },
        { code: "2347001", name: "Diagnostic model construction" },
        { code: "2364003", name: "Radical resection of tumor of soft tissue of wrist area" },
        { code: "2371008", name: "Tympanoplasty type II with graft against incus or malleus" },
        { code: "2373006", name: "Buffy coat smear evaluation" },
        { code: "2382000", name: "Application of breast pump" },
        { code: "2386002", name: "Closed reduction of dislocation of patella" },
        { code: "2393003", name: "Ligation of vein of lower limb" },
        { code: "2406000", name: "Chart periodontal pocket" },
        { code: "2407009", name: "Excision of mediastinal tumor" },
        { code: "2408004", name: "Hexosaminidase A and total hexosaminidase measurement, serum" },
        { code: "2409007", name: "Replantation of toe" },
        { code: "2425002", name: "Epstein-Barr virus serologic test" },
        { code: "2442008", name: "Incision of lacrimal canaliculus" },
        { code: "2448007", name: "Cell count of synovial fluid with differential count" },
        { code: "2455009", name: "Revision of lumbosubarachnoid shunt" },
        { code: "2457001", name: "Blind rehabilitation" },
        { code: "2458006", name: "Educational therapy" },
        { code: "2459003", name: "Destructive procedure of artery of upper extremity" },
        { code: "2461007", name: "Tennis elbow test" },
        { code: "2474001", name: "Repair of malunion of metatarsal bones" },
        { code: "2475000", name: "Twenty-four hour collection of urine" },
        { code: "2480009", name: "Debridement of skin, subcutaneous tissue, muscle and bone" },
        { code: "2486003", name: "Destructive procedure of breast" },
        { code: "2488002", name: "Provision of contact lens" },
        { code: "2494005", name: "Nurse to nurse communication" },
        { code: "2498008", name: "Rebase of upper partial denture" },
        { code: "2507007", name: "5' Nucleotidase measurement" },
        { code: "2508002", name: "Retrograde urography with kidney-ureter-bladder" },
        { code: "2514009", name: "Manual reduction of closed supracondylar fracture of humerus with traction" },
        { code: "2517002", name: "Stroke rehabilitation" },
        { code: "2530001", name: "Chiropractic visit" },
        { code: "2531002", name: "Mononuclear cell function assay" },
        { code: "2535006", name: "Removal of pulp - complete" },
        { code: "2536007", name: "Injection of medication in anterior chamber of eye" },
        { code: "2547000", name: "Excision of keloid" },
        { code: "2552005", name: "Incision of cerebral subarachnoid space" },
        { code: "2564002", name: "Creation of lumbar shunt including laminectomy" },
        { code: "2566000", name: "Osteoplasty of radius" },
        { code: "2567009", name: "Resection of rib by transaxillary approach" },
        { code: "2580007", name: "Transplant of hair follicles to scalp" },
        { code: "2598006", name: "Open heart surgery" },
        { code: "2601001", name: "Removal of bone flap of skull" },
        { code: "2607002", name: "Operation of supporting structures of uterus" },
        { code: "2613006", name: "Implantation of joint prosthesis of hand" },
        { code: "2614000", name: "Removal of ligature from fallopian tube" },
        { code: "2616003", name: "Repair of bifid digit of hand" },
        { code: "2619005", name: "Psychiatric interpretation to family or parents of patient" },
        { code: "2629003", name: "Intracranial/cerebral perfusion pressure monitoring" },
        { code: "2632000", name: "Incision and drainage of infected bursa of upper arm" },
        { code: "2642003", name: "Prefabricated post and core in addition to crown" },
        { code: "2643008", name: "Ligation of varicose vein of head and neck" },
        { code: "2644002", name: "Cauterization of liver" },
        { code: "2645001", name: "Intelligence test/WB1" },
        { code: "2646000", name: "Incision and exploration of vas deferens" },
        { code: "2658000", name: "Social service interview of patient" },
        { code: "2659008", name: "Suture of ligament of lower extremity" },
        { code: "2668005", name: "Recementation of space maintainer" },
        { code: "2670001", name: "Diagnostic procedure on cornea" },
        { code: "2673004", name: "Incision and drainage of masticator space by extraoral approach" },
        { code: "2677003", name: "Stripping" },
        { code: "2690005", name: "MRI of pelvis" },
        { code: "2693007", name: "Stool fat, quantitative measurement" },
        { code: "2696004", name: "Hepatic venography with hemodynamic evaluation" },
        { code: "2697008", name: "Stripping and ligation of great saphenous vein" },
        { code: "2716009", name: "Dermal-fat-fascia graft" },
        { code: "2722000", name: "Interleukin-3 assay" },
        { code: "2731000", name: "Serologic test for influenza virus A" },
        { code: "2732007", name: "Recession of tendon of hand" },
        { code: "2737001", name: "Exploratory craniotomy, infratentorial" },
        { code: "2742009", name: "Destruction of Bartholin's gland" },
        { code: "2743004", name: "Operative endoscopy of ileum" },
        { code: "2745006", name: "Epiplopexy" },
        { code: "2752008", name: "Incudopexy" },
        { code: "2780005", name: "Osteoplasty of facial bones" },
        { code: "2794006", name: "Cauterization of navel" },
        { code: "2802005", name: "Manual dilation and stretching" },
        { code: "2811005", name: "Cineradiography of pharynx" },
        { code: "2813008", name: "Nephroureterocystectomy" },
        { code: "2837008", name: "Transposition of ulnar nerve at elbow" },
        { code: "2842000", name: "Gas chromatography measurement" },
        { code: "2843005", name: "Revision of urinary conduit" },
        { code: "2847006", name: "Cervical myelography" },
        { code: "2851008", name: "Arthrotomy for synovectomy of sternoclavicular joint" },
        { code: "2854000", name: "Bursectomy of hand" },
        { code: "2857007", name: "Pinealectomy" },
        { code: "2866006", name: "Obliteration of lymphatic structure" },
        { code: "2875008", name: "Implantation of joint prosthesis of elbow" },
        { code: "2876009", name: "Hospital admission, type unclassified, explain by report" },
        { code: "2885009", name: "Intradermal allergen test" },
        { code: "2891006", name: "Arthroscopy of elbow with partial synovectomy" },
        { code: "2898000", name: "Deoxyribonucleic acid analysis, antenatal, blood" },
        { code: "2903001", name: "Diagnostic procedure on anterior chamber of eye" },
        { code: "2908005", name: "Cryotherapy to hemorrhoid" },
        { code: "2914003", name: "Anterior sclerotomy" },
        { code: "2915002", name: "Suture of capsule of ankle" },
        { code: "2933008", name: "Pneumogynecography" },
        { code: "2945004", name: "Suprapubic diverticulectomy of urinary bladder" },
        { code: "2947007", name: "Therapeutic compound measurement" },
        { code: "2960001", name: "Closure of fistula of uterine cervix" },
        { code: "2968008", name: "Craniectomy with treatment of penetrating wound of brain" },
        { code: "2970004", name: "Metacarpal lengthening and transfer of local flap" },
        { code: "2971000", name: "Closure of acquired urethrovaginal fistula" },
        { code: "2977001", name: "Thrombectomy of lower limb vein" },
        { code: "3001009", name: "Total lobectomy with bronchoplasty" },
        { code: "3010001", name: "Removal of silastic tubes from ear" },
        { code: "3016007", name: "Removal of Crutchfield tongs from skull" },
        { code: "3025001", name: "Calcitonin measurement" },
        { code: "3026000", name: "Tibiotalar arthrodesis" },
        { code: "3029007", name: "Peripheral nervous system disease rehabilitation" },
        { code: "3041000", name: "Repair of stomach" },
        { code: "3047001", name: "Kowa fundus photography" },
        { code: "3060007", name: "Forequarter amputation, right" },
        { code: "3061006", name: "Complete excision of nail AND nail matrix" },
        { code: "3063009", name: "Gastroscopy through artificial stoma" },
        { code: "3075004", name: "Nonoperative removal of prosthesis of bile duct" },
        { code: "3078002", name: "Embolectomy with catheter of renal artery by abdominal incision" },
        { code: "3083005", name: "Removal of device from thorax" },
        { code: "3088001", name: "Anesthesia for endoscopic procedure on upper extremity" },
        { code: "3090000", name: "Aneurysmectomy with graft replacement of lower limb artery" },
        { code: "3112006", name: "Restraint removal" },
        { code: "3116009", name: "Clotting screening" },
        { code: "3130004", name: "Monitoring of cardiac output by electrocardiogram" },
        { code: "3133002", name: "Patient discharge, deceased, autopsy" },
        { code: "3137001", name: "Replacement" },
        { code: "3143004", name: "Visual field examination and evaluation, intermediate" },
        { code: "3162001", name: "Gadolinium measurement" },
        { code: "3164000", name: "Open reduction of closed mandibular fracture with interdental fixation" },
        { code: "3165004", name: "Irrigation of muscle of hand" },
        { code: "3166003", name: "Closure of fistula of salivary gland" },
        { code: "3177009", name: "Internal obstetrical version" },
        { code: "3183007", name: "Closure of colostomy" },
        { code: "3186004", name: "Excision of Skene gland" },
        { code: "3190002", name: "Epilation by forceps" },
        { code: "3204007", name: "Destructive procedure of nerve" },
        { code: "3241008", name: "Correction of chordee with mobilization of urethra" },
        { code: "3249005", name: "Surgical construction of filtration bleb" },
        { code: "3251009", name: "Mayo operation, herniorrhaphy" },
        { code: "3256004", name: "Cervical lymphangiogram" },
        { code: "3257008", name: "Empty and measure peritoneal dialysis fluid" },
        { code: "3258003", name: "Cerebral arteriography" },
        { code: "3268008", name: "Transplantation of tissue of pelvic region" },
        { code: "3270004", name: "Implantation of neurostimulator in spine" },
        { code: "3278006", name: "Lysis of adhesions of bursa of hand" },
        { code: "3287002", name: "Cholecystogastrostomy" },
        { code: "3320000", name: "Abt - autologous blood transfusion" },
        { code: "3324009", name: "Laser beam photocoagulation" },
        { code: "3326006", name: "Excision of exostosis of head of fifth metatarsal" },
        { code: "3328007", name: "Incision of vein of head and neck" },
        { code: "3333006", name: "Application of short arm splint, forearm to hand, static" },
        { code: "3338002", name: "Open reduction of open radial shaft fracture" },
        { code: "3352000", name: "PTH - Parathyroid hormone level" },
        { code: "3357006", name: "Iron kinetics" },
        { code: "3360004", name: "Biliary anastomosis" },
        { code: "3390006", name: "Verification procedure" },
        { code: "3399007", name: "Reduction of torsion of omentum" },
        { code: "3407002", name: "Creation of lesion of spinal cord by percutaneous method" },
        { code: "3413006", name: "Blood cell morphology" },
        { code: "3418002", name: "Chondrectomy of spine" },
        { code: "3432000", name: "Preventive dental service" },
        { code: "3443008", name: "Pulp capping" },
        { code: "3448004", name: "Fixation of contralateral testis" },
        { code: "3450007", name: "Lymphocytes, T & B cell evaluation" },
        { code: "3457005", name: "Referral procedure" },
        { code: "3479000", name: "Removal of heart assist system with replacement" },
        { code: "3498003", name: "Total excision of pituitary gland by transsphenoidal approach" },
        { code: "3499006", name: "Aspiration of vitreous with replacement" },
        { code: "3509001", name: "Streptococcus vaccination" },
        { code: "3512003", name: "Angiography of arteries of extremity" },
        { code: "3515001", name: "Replacement of electronic heart device, pulse generator" },
        { code: "3517009", name: "Removal of foreign body of pelvis from subcutaneous tissue" },
        { code: "3518004", name: "Aversive psychotherapy" },
        { code: "3527003", name: "Antibody measurement" },
        { code: "3546002", name: "CVG - Coronary vein graft" },
        { code: "3559005", name: "Insertion of ureteral stent with ureterotomy" },
        { code: "3562008", name: "Rodney Smith operation, radical subtotal pancreatectomy" },
        { code: "3564009", name: "Removal of foreign body from fallopian tube" },
        { code: "3575008", name: "Repair of fascia with graft of fascia" },
        { code: "3580004", name: "Removal of calculus of pharynx" },
        { code: "3605001", name: "Reduction of ciliary body" },
        { code: "3607009", name: "Transplantation of mesenteric tissue" },
        { code: "3620007", name: "Red cell survival study with hepatic sequestration" },
        { code: "3625002", name: "Anesthesia for brachial arteriograms, retrograde" },
        { code: "3651000", name: "Morphometric analysis, nerve" },
        { code: "3654008", name: "Excision of lingula" },
        { code: "3659003", name: "Incision of inner ear" },
        { code: "3664004", name: "Closure of scleral fistula" },
        { code: "3666002", name: "Repair of peripheral nerve by suturing" },
        { code: "3669009", name: "Fitting of prosthesis or prosthetic device of upper arm" },
        { code: "3673007", name: "Leadbetter urethral reconstruction" },
        { code: "3683006", name: "Selenium measurement, urine" },
        { code: "3686003", name: "Zancolli operation for tendon transfer of biceps" },
        { code: "3688002", name: "Anesthesia for lens surgery" },
        { code: "3690001", name: "Shunt of left subclavian to descending aorta by Blalock-Park operation" },
        { code: "3691002", name: "Wedge osteotomy of tarsals and metatarsals" },
        { code: "3697003", name: "Tissue processing technique, routine, embed, cut and stain, per autopsy" },
        { code: "3700004", name: "Erysophake extraction of lens" },
        { code: "3701000", name: "Removal of foreign body of hip from subcutaneous tissue" },
        { code: "3713005", name: "Release for de Quervain tenosynovitis of hand" },
        { code: "3717006", name: "Dilute Russell viper venom time" },
        { code: "3734003", name: "SSG - Split skin graft" },
        { code: "3735002", name: "Coproporphyrin III measurement" },
        { code: "3740005", name: "Removal of foreign body of canthus by incision" },
        { code: "3748003", name: "Biopsy of perirenal tissue" },
        { code: "3749006", name: "Reduction of closed ischial fracture" },
        { code: "3758004", name: "Thrombectomy with catheter of subclavian artery by neck incision" },
        { code: "3770000", name: "Ward urine dip stick testing" },
        { code: "3778007", name: "Scrotum manipulation" },
        { code: "3780001", name: "Routine patient disposition, no follow-up planned" },
        { code: "3784005", name: "Delayed hypersensitivity skin test for streptokinase-streptodornase" },
        { code: "3786007", name: "Excision of lesion of pharynx" },
        { code: "3787003", name: "Ultrasonic guidance for needle biopsy" },
        { code: "3794000", name: "Pregnanetriol measurement" },
        { code: "3796003", name: "Excision of redundant mucosa from jejunostomy" },
        { code: "3799005", name: "Radiography of adenoids" },
        { code: "3802001", name: "Topical application of tooth medicament - desensitizing agent" },
        { code: "3819004", name: "Embolization of thoracic artery" },
        { code: "3826004", name: "Blepharotomy with drainage of abscess of eyelid" },
        { code: "3828003", name: "Open biopsy of vertebral body of thoracic region" },
        { code: "3831002", name: "Chiropractic application of ice" },
        { code: "3843001", name: "Removal of foreign body from fascia" },
        { code: "3858009", name: "Echography of thyroid, A-mode" },
        { code: "3861005", name: "Aneurysmectomy with anastomosis of lower limb artery" },
        { code: "3862003", name: "Total vital capacity measurement" },
        { code: "3864002", name: "Excisional biopsy of scrotum" },
        { code: "3880007", name: "Excision of lesion of fibula" },
        { code: "3881006", name: "Incision and drainage of submental space by extraoral approach" },
        { code: "3887005", name: "Wart ligation" },
        { code: "3889008", name: "Suture of lip" },
        { code: "3891000", name: "Comprehensive orthodontic treatment, permanent dentition, for class I malocclusion" },
        { code: "3895009", name: "Dressing" },
        { code: "3907006", name: "Incision and drainage of retroperitoneal abscess" },
        { code: "3911000", name: "Transplantation of muscle" },
        { code: "3915009", name: "Excision of artery of thorax and abdomen" },
        { code: "3917001", name: "Excisional biopsy of phalanges of foot" },
        { code: "3918006", name: "Plastic repair with lengthening" },
        { code: "3926003", name: "Lactate measurement" },
        { code: "3929005", name: "Patient transfer, in-hospital, bed-to-bed" },
        { code: "3936006", name: "Making Foster bed" },
        { code: "3938007", name: "Cerclage for retinal reattachment" },
        { code: "3942005", name: "Cystopexy" },
        { code: "3955006", name: "Antibody elution from red blood cells" },
        { code: "3957003", name: "Arteriectomy of thoracoabdominal aorta" },
        { code: "3963007", name: "Operation on submaxillary gland" },
        { code: "3967008", name: "Fluorescence polarization immunoassay" },
        { code: "3968003", name: "Excision of spinal facet joint" },
        { code: "3969006", name: "Removal of osteocartilagenous loose body from joint structures" },
        { code: "3971006", name: "Duchenne muscular dystrophy carrier detection" },
        { code: "3980006", name: "Partial excision of esophagus" },
        { code: "3981005", name: "Carrier detection, molecular genetics" },
        { code: "3985001", name: "Anesthesia for procedure on arteries of lower leg with bypass graft" },
        { code: "3991004", name: "MRI of pelvis, prostate and bladder" },
        { code: "3998005", name: "Bone imaging of limited area" },
        { code: "4007002", name: "Anti-human globulin test, indirect, titer, non-gamma" },
        { code: "4008007", name: "Phlebography of neck" },
        { code: "4010009", name: "Oophorectomy of remaining ovary with tube" },
        { code: "4027001", name: "Implantation of electronic stimulator into phrenic nerve" },
        { code: "4034004", name: "Closed reduction of facial fracture, except mandible" },
        { code: "4035003", name: "Restoration, resin, two surfaces, posterior, permanent" },
        { code: "4036002", name: "Arthroscopy of elbow with extensive debridement" },
        { code: "4037006", name: "Removal of vascular graft or prosthesis" },
        { code: "4044002", name: "Construction of permanent colostomy" },
        { code: "4045001", name: "Drainage of cerebral ventricle by incision" },
        { code: "4052004", name: "Percutaneous aspiration of spinal cord cyst" },
        { code: "4064007", name: "Specimen aliquoting" },
        { code: "4068005", name: "Removal of ventricular reservoir with synchronous replacement" },
        { code: "4083000", name: "Fitting of prosthesis or prosthetic device of lower arm" },
        { code: "4084006", name: "Repair of tendon of hand by graft or implant of muscle" },
        { code: "4090005", name: "Replacement of transvenous atrial and ventricular pacemaker electrode leads" },
        { code: "4094001", name: "Reduction of retroversion of uterus by suppository" },
        { code: "4101004", name: "Revision of spinal pleurothecal shunt" },
        { code: "4102006", name: "Root canal therapy, anterior, excluding final restoration" },
        { code: "4114003", name: "Parenteral chemotherapy for malignant neoplasm" },
        { code: "4116001", name: "Construction of window" },
        { code: "4119008", name: "Intracranial phlebectomy with anastomosis" },
        { code: "4131005", name: "Implantation into pelvic region" },
        { code: "4134002", name: "Operative block anesthesia" },
        { code: "4139007", name: "Posterior spinal cordotomy" },
        { code: "4143006", name: "Injection into anterior chamber of eye" },
        { code: "4149005", name: "Bone histomorphometry, aluminum stain" },
        { code: "4154001", name: "Incision and drainage of penis" },
        { code: "4165006", name: "Delayed hypersensitivity skin test for staphage lysate" },
        { code: "4176005", name: "Fothergill repair" },
        { code: "4192000", name: "Toxicology testing for organophosphate insecticide" },
        { code: "4213001", name: "Implantation of Ommaya reservoir" },
        { code: "4214007", name: "Intracardiac injection for cardiac resuscitation" },
        { code: "4226002", name: "Excision of lesion of thoracic vein" },
        { code: "4252008", name: "Aneurysmectomy with graft replacement by interposition" },
        { code: "4263006", name: "Biopsy of soft tissue of elbow area, superficial" },
        { code: "4266003", name: "Patient referral for drug addiction rehabilitation" },
        { code: "4285000", name: "Insertion of bone growth stimulator into femur" },
        { code: "4293000", name: "Reduction of intussusception by laparotomy" },
        { code: "4304000", name: "Excision of cusp of tricuspid valve" },
        { code: "4319004", name: "Rebase of complete lower denture" },
        { code: "4321009", name: "Bilateral leg arteriogram" },
        { code: "4323007", name: "Destruction of lesion of sclera" },
        { code: "4331002", name: "Anesthesia for hernia repair in lower abdomen" },
        { code: "4333004", name: "Incision and drainage of perisplenic space" },
        { code: "4336007", name: "Lloyd-Davies operation, abdominoperineal resection" },
        { code: "4337003", name: "Homogentisic acid measurement" },
        { code: "4339000", name: "Repair of nasolabial fistula" },
        { code: "4341004", name: "Complete submucous resection of turbinate" },
        { code: "4344007", name: "Cryopexy" },
        { code: "4348005", name: "Musculoplasty of hand" },
        { code: "4350002", name: "Removal of implant of cornea" },
        { code: "4363008", name: "Endoscopic brush biopsy of trachea" },
        { code: "4365001", name: "Surgical repair" },
        { code: "4380007", name: "Transposition of vulvar tissue" },
        { code: "4387005", name: "Valvuloplasty of pulmonary valve in total repair of tetralogy of Fallot" },
        { code: "4388000", name: "Repair of splenocolic fistula" },
        { code: "4407008", name: "Slitting of lacrimal canaliculus for passage of tube" },
        { code: "4411002", name: "Removal of device from female genital tract" },
        { code: "4420006", name: "Incision and drainage of parapharyngeal abscess by external approach" },
        { code: "4424002", name: "Making orthopedic bed" },
        { code: "4436008", name: "Methylatable chemotaxis protein (MCP) receptor measurement" },
        { code: "4438009", name: "Venography of vena cava" },
        { code: "4443002", name: "Decortication of ovary" },
        { code: "4447001", name: "Autopsy, gross and microscopic examination, stillborn or newborn without central nervous system" },
        { code: "4449003", name: "Manipulation of spinal meninges" },
        { code: "4450003", name: "Application of Kirschner wire" },
        { code: "4455008", name: "Open reduction of open elbow dislocation" },
        { code: "4457000", name: "Insertion of mold into vagina" },
        { code: "4466001", name: "Exploration of upper limb artery" },
        { code: "4467005", name: "Excision of tumor of ankle area, deep, intramuscular" },
        { code: "4475004", name: "Cyanide level" },
        { code: "4487006", name: "Norepinephrine measurement, supine" },
        { code: "4489009", name: "Neurolysis of trigeminal nerve" },
        { code: "4496006", name: "Mouthcare procedure" },
        { code: "4503005", name: "Removal of foreign body of sclera without use of magnet" },
        { code: "4504004", name: "Potter obstetrical version with extraction" },
        { code: "4505003", name: "Tenolysis of flexor tendon of forearm" },
        { code: "4507006", name: "Decompression fasciotomy of wrist, flexor and extensor compartment" },
        { code: "4511000", name: "Restoration, inlay, composite/resin, one surface, laboratory processed" },
        { code: "4516005", name: "Iridencleisis and iridotasis" },
        { code: "4520009", name: "Anastomosis of esophagus, antesternal or antethoracic, with insertion of prosthesis" },
        { code: "4525004", name: "Seen by casualty - service" },
        { code: "4533003", name: "Ligation of artery of lower limb" },
        { code: "4535005", name: "Incision of pelvirectal tissue" },
        { code: "4539004", name: "Excision of cyst of bronchus" },
        { code: "4542005", name: "Closed reduction of fracture of foot" },
        { code: "4544006", name: "Excision of subcutaneous tumor of extremities" },
        { code: "4558008", name: "Anterior resection of rectum" },
        { code: "4563007", name: "Hospital admission, transfer from other hospital or health care facility" },
        { code: "4570007", name: "Chemopallidectomy" },
        { code: "4579008", name: "Creation of ventriculoatrial shunt" },
        { code: "4581005", name: "Coreoplasty" },
        { code: "4585001", name: "Decompression of tendon of hand" },
        { code: "4587009", name: "Epiphysiodesis of distal radius" },
        { code: "4589007", name: "Care relating to reproduction and pregnancy" },
        { code: "4593001", name: "Cauterization of sclera with iridectomy" },
        { code: "4594007", name: "Coproporphyrin isomers, series I & III, urine" },
        { code: "4613005", name: "Radioimmunoassay" },
        { code: "4625008", name: "Apical pulse taking" },
        { code: "4626009", name: "Take-down of arterial anastomosis" },
        { code: "4636001", name: "Denker operation for radical maxillary antrotomy" },
        { code: "4640005", name: "Ligation of fallopian tubes by abdominal approach" },
        { code: "4642002", name: "Removal of inflatable penile prosthesis, with pump, reservoir and cylinders" },
        { code: "4660002", name: "Diagnostic procedure on phalanges of foot" },
        { code: "4670000", name: "Catheterization of bronchus" },
        { code: "4671001", name: "Excision of lesion from sphenoid sinus" },
        { code: "4672008", name: "Medical procedure on the nervous system" },
        { code: "4691008", name: "Identification of rotavirus antigen in feces" },
        { code: "4692001", name: "Transplantation of artery of upper extremity" },
        { code: "4694000", name: "Percutaneous biopsy of muscle" },
        { code: "4699005", name: "Alpha naphthyl butyrate stain method, blood or bone marrow" },
        { code: "4701005", name: "Colony forming unit-granulocyte-monocyte-erythroid-megakaryocyte assay" },
        { code: "4707009", name: "Partial excision of calcaneus" },
        { code: "4712005", name: "Removal of Gardner Wells tongs from skull" },
        { code: "4713000", name: "Endoscopy and photography" },
        { code: "4719001", name: "Psychologic cognitive testing and assessment" },
        { code: "4727005", name: "Lipoprotein electrophoresis" },
        { code: "4734007", name: "Irrigation of wound catheter of integument" },
        { code: "4737000", name: "Mycobacteria culture" },
        { code: "4756005", name: "Cryotherapy of subcutaneous tissue" },
        { code: "4758006", name: "Incudostapediopexy" },
        { code: "4764004", name: "Jet ventilation procedure" },
        { code: "4765003", name: "Insertion of ocular implant following or secondary to enucleation" },
        { code: "4770005", name: "Colporrhaphy for repair of urethrocele" },
        { code: "4772002", name: "Reduction of torsion of spermatic cord" },
        { code: "4784000", name: "Operation on sublingual gland" },
        { code: "4804005", name: "Microbial identification test" },
        { code: "4811009", name: "Reconstruction of diaphragm" },
        { code: "4815000", name: "Antibody identification, red blood cell antibody panel, enzyme, 2 stage technique including anti-human globulin" },
        { code: "4820000", name: "Incision of labial frenum" },
        { code: "4827002", name: "Shower hydrotherapy" },
        { code: "4829004", name: "Excision of small intestine for interposition" },
        { code: "4847005", name: "Anesthesia for cesarean section" },
        { code: "4849008", name: "Ovarian biopsy" },
        { code: "4862007", name: "Revision of anastomosis of large intestine" },
        { code: "4877004", name: "Extracapsular extraction of lens with iridectomy" },
        { code: "4891005", name: "Proctostomy" },
        { code: "4895001", name: "Construction of sigmoid bladder" },
        { code: "4902005", name: "Ethchlorvynol measurement" },
        { code: "4903000", name: "Serum protein electrophoresis" },
        { code: "4904006", name: "Dilation of anal sphincter under nonlocal anesthesia" },
        { code: "4914002", name: "Treatment planning for teletherapy" },
        { code: "4929000", name: "Local perfusion of kidney" },
        { code: "4930005", name: "Repair of thoracogastric fistula" },
        { code: "4934001", name: "Salpingography" },
        { code: "4957007", name: "Cervical spinal fusion for pseudoarthrosis" },
        { code: "4966006", name: "Extracorporeal perfusion" },
        { code: "4970003", name: "Venography" },
        { code: "4974007", name: "Liver operation" },
        { code: "4976009", name: "Anesthesia for endoscopic procedure on lower extremity" },
        { code: "4987001", name: "Osteoplasty of cranium with flap of bone" },
        { code: "4992004", name: "Cardiac catheterization, left heart, retrograde, percutaneous" },
        { code: "4993009", name: "Ischemic limb exercise with electromyography and lactic acid determination" },
        { code: "5016005", name: "Pontic, resin with high noble metal" },
        { code: "5019003", name: "Direct laryngoscopy with biopsy" },
        { code: "5021008", name: "Aldosterone measurement, standing, normal salt diet" },
        { code: "5022001", name: "Lysergic acid diethylamide measurement" },
        { code: "5025004", name: "Semen analysis, presence and motility of sperm" },
        { code: "5032008", name: "Labial veneer, porcelain laminate, laboratory" },
        { code: "5034009", name: "Graft to hair-bearing skin" },
        { code: "5048009", name: "External cephalic version with tocolysis" },
        { code: "5055006", name: "Uniscept system test" },
        { code: "5057003", name: "Radical orbitomaxillectomy" },
        { code: "5065000", name: "Reduction of closed traumatic hip dislocation with anesthesia" },
        { code: "5091004", name: "Peripheral vascular disease study" },
        { code: "5105000", name: "Endoscopy of renal pelvis" },
        { code: "5110001", name: "Ultrasound peripheral imaging, real time scan" },
        { code: "5113004", name: "FT4 - Free thyroxine level" },
        { code: "5119000", name: "Epiglottidectomy" },
        { code: "5121005", name: "Wedge osteotomy of pelvic bone" },
        { code: "5123008", name: "Anesthesia for procedure on pericardium with pump oxygenator" },
        { code: "5130002", name: "Needling of lens for cataract" },
        { code: "5131003", name: "Radiography of chest wall" },
        { code: "5135007", name: "Diagnostic procedure on scapula" },
        { code: "5147001", name: "Excision of lesion of ankle joint" },
        { code: "5151004", name: "Manual reduction of rectal hemorrhoids" },
        { code: "5154007", name: "Communication enhancement: speech deficit" },
        { code: "5161006", name: "Specialty clinic admission" },
        { code: "5162004", name: "Excision of pressure ulcer" },
        { code: "5165002", name: "Division of thoracic artery" },
        { code: "5176003", name: "Thromboendarterectomy with graft of renal artery" },
        { code: "5182000", name: "Total body perfusion" },
        { code: "5184004", name: "Osteotomy of shaft of femur with fixation" },
        { code: "5186002", name: "Arthrotomy for synovectomy of glenohumeral joint" },
        { code: "5190000", name: "Cell fusion" },
        { code: "5191001", name: "Surgical treatment of missed miscarriage of second trimester" },
        { code: "5212002", name: "Excision of lesion of lacrimal gland by frontal approach" },
        { code: "5216004", name: "Three dimensional ultrasound imaging of heart" },
        { code: "5233006", name: "Lateral fasciotomy" },
        { code: "5243009", name: "Suture of adenoid fossa" },
        { code: "5245002", name: "Transplantation of peripheral vein" },
        { code: "5246001", name: "Breakpoint cluster region analysis" },
        { code: "5264008", name: "Total bile acids measurement" },
        { code: "5267001", name: "Adrenal artery ligation" },
        { code: "5270002", name: "Bilateral destruction of fallopian tubes" },
        { code: "5273000", name: "Manual reduction of closed fracture of proximal end of ulna" },
        { code: "5282006", name: "Operation on oropharynx" },
        { code: "5290006", name: "Incision and drainage of Ludwig angina" },
        { code: "5298004", name: "Incision and drainage of deep hematoma of thigh region" },
        { code: "5304008", name: "DXT - Radiotherapy" },
        { code: "5316002", name: "Closed osteotomy of mandibular ramus" },
        { code: "5317006", name: "Radical amputation of penis with bilateral pelvic lymphadenectomy" },
        { code: "5326009", name: "Administration of dermatologic formulation" },
        { code: "5328005", name: "Shortening of Achilles tendon" },
        { code: "5337005", name: "Trocar biopsy" },
        { code: "5338000", name: "Nicotine measurement" },
        { code: "5342002", name: "Prophylactic treatment of tibia with methyl methacrylate" },
        { code: "5348003", name: "Repair of endocardial cushion defect" },
        { code: "5357009", name: "Leukocyte poor blood preparation" },
        { code: "5373003", name: "Stress breaker" },
        { code: "5384005", name: "Excision of part of frontal cortex" },
        { code: "5391008", name: "Artificial voice rehabilitation" },
        { code: "5393006", name: "Exploration of parathyroid with mediastinal exploration by sternal split approach" },
        { code: "5402006", name: "Manipulation of thoracic artery" },
        { code: "5407000", name: "Injection of fallopian tube" },
        { code: "5415002", name: "Destruction of lesion of liver" },
        { code: "5419008", name: "Lysis of adhesions of tendon of hand" },
        { code: "5422005", name: "Amylase measurement, peritoneal fluid" },
        { code: "5429001", name: "Diagnostic procedure on nipple" },
        { code: "5431005", name: "Percutaneous transluminal angioplasty" },
        { code: "5433008", name: "Skeletal X-ray of lower limb" },
        { code: "5446003", name: "Excision of cervical rib for outlet compression syndrome with sympathectomy" },
        { code: "5447007", name: "Transfusion" },
        { code: "5452002", name: "Core needle biopsy of thymus" },
        { code: "5456004", name: "Graft of lymphatic structure" },
        { code: "5457008", name: "Serologic test for Rickettsia conorii" },
        { code: "5460001", name: "Removal of prosthesis from fallopian tube" },
        { code: "5479003", name: "Select picture audiometry" },
        { code: "5482008", name: "Serologic test for Blastomyces" },
        { code: "5486006", name: "Delayed suture of tendon of hand" },
        { code: "5489004", name: "Diagnostic procedure on radius" },
        { code: "5506006", name: "Incision and exploration of abdominal wall" },
        { code: "5517007", name: "Restoration, inlay, porcelain/ceramic, per tooth, in addition to inlay" },
        { code: "5521000", name: "Open reduction of fracture of phalanges of foot" },
        { code: "5536002", name: "Arthrodesis of carpometacarpal joint of digits, other than thumb" },
        { code: "5545001", name: "Repair of carotid body" },
        { code: "5551006", name: "Direct laryngoscopy with arytenoidectomy with operating microscope" },
        { code: "5556001", name: "Manually assisted spontaneous delivery" },
        { code: "5570001", name: "Arthrotomy for infection with exploration and drainage of carpometacarpal joint" },
        { code: "5571002", name: "Excision of lesion of aorta with end-to-end anastomosis" },
        { code: "5572009", name: "Incision of kidney pelvis" },
        { code: "5586008", name: "Aminolevulinic acid dehydratase measurement" },
        { code: "5608002", name: "Excretion measurement" },
        { code: "5616006", name: "Osteoplasty of tibia" },
        { code: "5621009", name: "Excision of malignant lesion of skin of extremities" },
        { code: "5632009", name: "Open biopsy of bronchus" },
        { code: "5636007", name: "Fistulectomy of bone" },
        { code: "5638008", name: "Carbohydrate measurement" },
        { code: "5648005", name: "Surgical repair and revision of shunt" },
        { code: "5651003", name: "Arylsulfatase A measurement" },
        { code: "5663008", name: "Phlebectomy of varicose vein of head and neck" },
        { code: "5669007", name: "Portable electroencephalogram awake and asleep with stimulation" },
        { code: "5671007", name: "Magnet extraction of foreign body from ciliary body" },
        { code: "5687005", name: "Removal of foreign body from ovary" },
        { code: "5690004", name: "Incision of seminal vesicle" },
        { code: "5694008", name: "Crisis intervention with follow-up" },
        { code: "5721002", name: "Repair of eyebrow" },
        { code: "5722009", name: "Surgical reanastomosis of colon" },
        { code: "5726007", name: "Removal of epicardial electrodes" },
        { code: "5728008", name: "Anoscopy for removal of foreign body" },
        { code: "5731009", name: "Hemosiderin, quantitative measurement" },
        { code: "5733007", name: "Fluorescent identification of anti-nuclear antibody" },
        { code: "5738003", name: "Biopsy of cul-de-sac" },
        { code: "5745003", name: "Excision ampulla of Vater with reimplantation of common duct" },
        { code: "5760000", name: "Osteoplasty of radius and ulna, shortening" },
        { code: "5771004", name: "Blepharotomy" },
        { code: "5777000", name: "Flexorplasty of elbow" },
        { code: "5781000", name: "Operation on nasal septum" },
        { code: "5785009", name: "Forensic autopsy" },
        { code: "5787001", name: "Elevation of bone fragments of orbit of skull with debridement" },
        { code: "5789003", name: "Lysis of adhesions of intestines" },
        { code: "5796001", name: "Excision of external thrombotic hemorrhoid" },
        { code: "5806001", name: "Revision of tracheostomy scar" },
        { code: "5807005", name: "Fenestration of inner ear, initial" },
        { code: "5809008", name: "Selective vagotomy with pyloroplasty and gastrostomy" },
        { code: "5812006", name: "Laboratory reporting, fax" },
        { code: "5818005", name: "Flocculation test" },
        { code: "5821007", name: "Ligation, division and complete stripping of long and short saphenous veins" },
        { code: "5823005", name: "Diagnostic radiography, left" },
        { code: "5832007", name: "Partial ostectomy of thorax, ribs or sternum" },
        { code: "5845006", name: "Emulsification procedure" },
        { code: "5846007", name: "Diagnostic radiography of toes" },
        { code: "5857002", name: "Complement mediated cytotoxicity assay" },
        { code: "5865004", name: "Open reduction of dislocation of toe" },
        { code: "5870006", name: "Tertiary closure of abdominal wall" },
        { code: "5880005", name: "Clinical examination" },
        { code: "5892005", name: "Mastoid antrotomy" },
        { code: "5894006", name: "Methyl red test" },
        { code: "5897004", name: "Removal of Scribner shunt" },
        { code: "5902003", name: "History and physical examination, complete" },
        { code: "5925002", name: "Incision and drainage of hematoma of wrist" },
        { code: "5930003", name: "Cardiac monitor removal" },
        { code: "5947002", name: "Consultation for hearing and/or speech problem" },
        { code: "5961007", name: "Division of blood vessels of cornea" },
        { code: "5966002", name: "Removal of foreign body from elbow area, deep" },
        { code: "5971009", name: "Incision and drainage of axilla" },
        { code: "5983006", name: "Repair of spermatic cord" },
        { code: "5986003", name: "Non-sensitized spontaneous sheep erythrocyte binding, E-rosette" },
        { code: "5992009", name: "Midtarsal arthrodesis, multiple" },
        { code: "5995006", name: "Gas liquid chromatography, flame photometric type" },
        { code: "5997003", name: "Drainage of cerebral subarachnoid space by aspiration" },
        { code: "5998008", name: "Radical dissection of groin" },
        { code: "6005008", name: "Transplantation of vitreous by anterior approach" },
        { code: "6007000", name: "Magnetic resonance imaging of chest" },
        { code: "6019008", name: "Endoscopy of large intestine" },
        { code: "6025007", name: "Laparoscopic appendectomy" },
        { code: "6026008", name: "Removal of coronary artery obstruction by percutaneous transluminal balloon with thrombolytic agent" },
        { code: "6029001", name: "Augmentation of outflow tract of pulmonary valve" },
        { code: "6035001", name: "Chart abstracting" },
        { code: "6063004", name: "Kanamycin measurement" },
        { code: "6069000", name: "Panniculotomy" },
        { code: "6082008", name: "Perforation of footplate" },
        { code: "6092000", name: "Aspiration of nasal sinus by puncture" },
        { code: "6100001", name: "Fenestration of stapes footplate with vein graft" },
        { code: "6108008", name: "Subdural tap through fontanel, infant, initial" },
        { code: "6119006", name: "Local destruction of lesion of bony palate" },
        { code: "6125005", name: "Change of gastrostomy tube" },
        { code: "6126006", name: "Fitzgerald factor assay" },
        { code: "6127002", name: "Diagnostic radiography of abdomen, oblique standard" },
        { code: "6130009", name: "Surgical exposure of impacted or unerupted tooth to aid eruption" },
        { code: "6133006", name: "Lymphokine assay" },
        { code: "6143009", name: "Diabetic education" },
        { code: "6146001", name: "Repair of heart septum with prosthesis" },
        { code: "6148000", name: "Chondrectomy of semilunar cartilage of knee" },
        { code: "6157006", name: "Endoscopic retrograde cholangiopancreatography with biopsy" },
        { code: "6159009", name: "Galactose measurement" },
        { code: "6161000", name: "Excision of lesion of capsule of toes" },
        { code: "6164008", name: "Osteoclasis of clavicle" },
        { code: "6166005", name: "Nephropyeloureterostomy" },
        { code: "6177004", name: "Southern blot assay" },
        { code: "6187000", name: "Repair of aneurysm with graft of common femoral artery" },
        { code: "6188005", name: "Arthrotomy of knee" },
        { code: "6189002", name: "Excision of aberrant tissue of breast" },
        { code: "6190006", name: "Colopexy" },
        { code: "6195001", name: "Transurethral drainage of prostatic abscess" },
        { code: "6198004", name: "Repair of fracture with Sofield type procedure" },
        { code: "6200005", name: "Excision of lesion of female perineum" },
        { code: "6205000", name: "Fluorescent antigen, titer" },
        { code: "6213004", name: "Prescribing corneoscleral contact lens" },
        { code: "6221005", name: "Suture of colon" },
        { code: "6225001", name: "Antibody detection, RBC, enzyme, 2 stage technique, including anti-human globulin" },
        { code: "6226000", name: "Visual rehabilitation, eye motion defect" },
        { code: "6227009", name: "Relationship psychotherapy" },
        { code: "6231003", name: "Graft of palate" },
        { code: "6238009", name: "Diagnostic radiography of sacroiliac joints" },
        { code: "6240004", name: "Operative procedure on knee" },
        { code: "6255008", name: "Resection of abdominal artery with replacement" },
        { code: "6271008", name: "Echography, immersion B-scan" },
        { code: "6274000", name: "Excision of aural glomus tumor, extended, extratemporal" },
        { code: "6286002", name: "Destructive procedure on ovaries and fallopian tubes" },
        { code: "6289009", name: "White blood cell histogram evaluation" },
        { code: "6295005", name: "Sequestrectomy of pelvic bone" },
        { code: "6307005", name: "Keratophakia" },
        { code: "6309008", name: "Fecal fat differential, quantitative" },
        { code: "6319002", name: "Beta lactamase, chromogenic cephalosporin susceptibility test" },
        { code: "6337001", name: "Ligation of aortic arch" },
        { code: "6339003", name: "Conditioning play audiometry" },
        { code: "6343004", name: "Forensic bite mark comparison technique" },
        { code: "6353003", name: "Mitsuda reaction to lepromin" },
        { code: "6354009", name: "Sedimentation rate, Westergren" },
        { code: "6355005", name: "Removal of internal fixation device of radius" },
        { code: "6358007", name: "Capsulorrhaphy of joint" },
        { code: "6361008", name: "Anesthesia for popliteal thromboendarterectomy" },
        { code: "6363006", name: "Dilation of lacrimal punctum with irrigation" },
        { code: "6370006", name: "Chemosurgery of stomach lesion" },
        { code: "6384001", name: "Removal of device from digestive system" },
        { code: "6385000", name: "Exploration of disc space" },
        { code: "6388003", name: "TdT stain" },
        { code: "6396008", name: "Galactokinase measurement" },
        { code: "6397004", name: "Muscular strength development exercise" },
        { code: "6399001", name: "Division of arteriovenous fistula with ligation" },
        { code: "6402000", name: "Excision of common bile duct" },
        { code: "6403005", name: "Lengthening of muscle of hand" },
        { code: "6419003", name: "Excision of tumor from elbow area, deep, subfascial" },
        { code: "6429005", name: "Heteroautogenous transplantation" },
        { code: "6433003", name: "Closed heart valvotomy of mitral valve" },
        { code: "6434009", name: "Seminal fluid detection" },
        { code: "6438007", name: "Exploration of ciliary body" },
        { code: "6439004", name: "Destruction of lesion of peripheral nerve" },
        { code: "6443000", name: "Pontic, porcelain fused to predominantly base metal" },
        { code: "6444006", name: "Enlargement of eye socket" },
        { code: "6465000", name: "Arthrotomy of glenohumeral joint for infection with drainage" },
        { code: "6466004", name: "Administration of Rh immune globulin" },
        { code: "6470007", name: "Laparoamnioscopy" },
        { code: "6473009", name: "Suture of old obstetrical laceration of uterus" },
        { code: "6480006", name: "Urinary bladder residual urine study" },
        { code: "6486000", name: "Curettage of sclera" },
        { code: "6487009", name: "Hand tendon pulley reconstruction with tendon prosthesis" },
        { code: "6491004", name: "Protein S, free assay" },
        { code: "6499002", name: "Tsuge operation on finger for macrodactyly repair" },
        { code: "6502003", name: "Complete lower denture" },
        { code: "6506000", name: "Placing a patient on a bedpan" },
        { code: "6519001", name: "Operation on multiple extraocular muscles with temporary detachment from globe" },
        { code: "6521006", name: "Polytomography" },
        { code: "6527005", name: "Uchida fimbriectomy with tubal ligation by endoscopy" },
        { code: "6535008", name: "Excision of cyst of hand" },
        { code: "6536009", name: "Implantation of tricuspid valve with tissue graft" },
        { code: "6543003", name: "Complicated catheterization of bladder" },
        { code: "6547002", name: "Repair with closure of non-surgical wound" },
        { code: "6555009", name: "Insertion of infusion pump beneath skin" },
        { code: "6556005", name: "Reticulin antibody measurement" },
        { code: "6562000", name: "Destruction of lesion of tongue" },
        { code: "6563005", name: "Transposition of muscle of hand" },
        { code: "6567006", name: "Pulmonary valve commissurotomy by transvenous balloon method" },
        { code: "6568001", name: "Diagnostic procedure on eyelid" },
        { code: "6585004", name: "Closed reduction of fracture of tarsal or metatarsal" },
        { code: "6589005", name: "Antibody titration, high protein" },
        { code: "6601003", name: "Removal of foreign body from skin of axilla" },
        { code: "6614002", name: "Antibody to single stranded DNA measurement" },
        { code: "6615001", name: "Electroretinography with medical evaluation" },
        { code: "6622009", name: "Add clasp to existing partial denture" },
        { code: "6634001", name: "Destruction of hemorrhoids, internal" },
        { code: "6639006", name: "Replacement of obstructed valve in shunt system" },
        { code: "6650009", name: "Radionuclide lacrimal flow study" },
        { code: "6656003", name: "Acoustic stimulation test" },
        { code: "6657007", name: "Maintenance drug therapy for mental disorder" },
        { code: "6658002", name: "Removal of foreign body from alveolus" },
        { code: "6661001", name: "King-Steelquist hindquarter operation" },
        { code: "6665005", name: "Restoration, crown, porcelain fused to noble metal" },
        { code: "6668007", name: "Fibrinogen assay, quantitative" },
        { code: "6670003", name: "Closure of external fistula of trachea" },
        { code: "6670005", name: "Acute Gastritis" },
        { code: "6670006", name: "Blood Sugar Fluctuation" },
        { code: "6670007", name: "Fluctuating Blood Pressure" },
        { code: "6670008", name: "Breathing difficulty" },

    ]
    const givenReportName = new RegExp(typeName.toLowerCase().trim())
    var returnCode
    procedure.forEach(element => {
        var elementName = element.name.toLowerCase()
        if (givenReportName.test(elementName)) {
            returnCode = element.code
        }
    });
    returnCode = returnCode == undefined ? 'No Such code found for report' : returnCode
    return returnCode
}

module.exports = mapRecordType